### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ghost** [AdamBrodzinski/react-ive-meteor#14]
```
users-MacBook-Pro:reactive user$ make dev
meteor \
        --port 3000 \
      --settings '.config/devel/settings.json'
[[[[[ ~/reactive ]]]]]

=> Started proxy.

=> Meteor 1.1.0.3: fixes Facebook integration for new apps.


This release is being downloaded in the background. Update your app to
Meteor 1.1.0.3 by running 'meteor update'.

=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `compileScss` from package `fourseven:scss`:
   module.js:356:32:
   dlopen(/Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node,
   1): Symbol not found: __ZNSt12out_of_rangeD1Ev
   Referenced from:
   /Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   Expected in: /usr/lib/libstdc++.6.dylib
   in
   /Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:16:15)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require
   (/Users/user/.meteor/packages/meteor-tool/.1.1.3.dzw9kd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1341:22)
   at Package (packages/compileScss/plugin/compile-scss.js:2:1)
   at <runJavaScript-30>:146:4
   at <runJavaScript-30>:153:3


=> Your application has errors. Waiting for file change.
```

**Comment by AdamBrodzinski** [comment]
Hmmm that's odd... can you try doing a `meteor reset`?

**Comment by ghost** [comment]
Still having the same error

```
users-MacBook-Pro:reactive user$ meteor reset
Project reset.
users-MacBook-Pro:reactive user$ meteor
[[[[[ ~/reactive ]]]]]

=> Started proxy.
=> Meteor 1.1.0.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Errors prevented startup:

   While loading plugin `compileScss` from package `fourseven:scss`:
   module.js:356:32:
   dlopen(/Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node,
   1): Symbol not found: __ZNSt12out_of_rangeD1Ev
   Referenced from:
   /Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   Expected in: /usr/lib/libstdc++.6.dylib
   in
   /Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/vendor/darwin-x64-11/binding.node
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
   (/Users/user/.meteor/packages/fourseven_scss/.3.1.1.vg4ybo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/compileScss/node_modules/node-sass/lib/index.js:16:15)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object._.extend.Npm.require (/Users/user/.meteor/packages/meteor-tool/.1.1.3.dzw9kd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/bundler.js:1341:22)
   at Package (packages/compileScss/plugin/compile-scss.js:2:1)
   at <runJavaScript-30>:146:4
   at <runJavaScript-30>:153:3


=> Your application has errors. Waiting for file change.
```

**Comment by ghost** [comment]
Worked after changing scss compiler packages.

Btw, only react package couldn't be updated even I use `meteor add react@latestVersion`
